services:

  spring:
    container_name: today_back
    image: spring:latest
    restart: always
    env_file:
      - /env/.env
    expose:
      - 8080"
    environment:
      TZ: Asia/Seoul

networks:
  default:
    name: today-net
    external: true